### ISSUE TITLE
Tried running the example, but I'm doing something wrong 😰

### ISSUE THREAD

**Issue by alextes** [edorivai/nock-record#3]
Slightly adapted the example to run by itself, unfortunately the test fails.

Adapted example:
```js
import { setupRecorder } from "jest-nock-record";
import got from 'got';

const record = setupRecorder();
const getProfile = () => got("https://api.github.com/users/alextes", { json: true });

describe("#getUserAgent", () => {
  it("should retrieve user agent", async () => {
    // Start recording, specify fixture name
    const { completeRecording, assertScopesFinished } = await record("httpbin");

    // Run your function under test
    const result = await getProfile();

    // Complete the recording, allow for Nock to write fixtures
    completeRecording();
    // Optional; assert that all recorded fixtures have been called
    assertScopesFinished();

    // Perform your own assertionsAllow
    expect(result).toMatchSnapshot();
  });
});

```
```
 FAIL  ./index.test.js
  #getUserAgent
    ✕ should retrieve user agent (35ms)

  ● #getUserAgent › should retrieve user agent

    RequestError: Nock: Not allow net connect for "api.github.com:443/users/alextes"

      at ErroringClientRequest.req.once.err (node_modules/got/index.js:182:22)
      at ErroringClientRequest.<anonymous> (node_modules/nock/lib/intercept.js:231:10)

```

Perhaps side-issue, perhaps misunderstanding of nock. Another test that works perfectly fine by itself now fails too with the same error:
```js
import got from 'got';

const getProfile = () => got("https://api.github.com/users/alextes", { json: true, timeout: 1000 });

test('get users', async () => {
  const { body } = await getProfile();
  expect(body).toMatchSnapshot();
})
```

**Comment by alextes** [comment]
Hmm, this issue appears related to a snapshot existing, and part of the system feeling a request should go through whilst another part is blocking the response.

After cleaning up the recordings it seems there's also an issue with got pushing bytes after a stream is closed which seems unrelated. Works when using `isomorphic-fetch`! e.g.
```js
import { setupRecorder } from "jest-nock-record";
import got from 'got';
import fetch from 'isomorphic-fetch';

const record = setupRecorder();
const getProfile = () => fetch("https://api.github.com/users/alextes");

describe("#getUserAgent", () => {
  it("should retrieve user agent", async () => {
    // Start recording, specify fixture name
    const { completeRecording, assertScopesFinished } = await record("userProfile");

    // Run your function under test
    const result = await getProfile().then(res => res.json());

    // Complete the recording, allow for Nock to write fixtures
    completeRecording();
    // Optional; assert that all recorded fixtures have been called
    assertScopesFinished();

    // Perform your own assertionsAllow
    expect(result).toMatchSnapshot();
  });
});
```
